# August 21, 2015
# https://docpad.org/docs/deploy

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - iojs
cache:
  directories:
    - node_modules

# Prepare and run our tests
script: "npm test"

# Custom Notifications
# travis encrypt "$TRAVIS_NOTIFICATION_EMAIL" --add notifications.email.recipients
# travis encrypt "$SLACK_SUBDOMAIN:$SLACK_TRAVIS_TOKEN#updates" --add notifications.slack
notifications:
  email:
    recipients:
      secure: R6iR1oq4QYgIJXV5iDPUbMl6ZC6Pq3TYERBW8xGoGt5YrZKthR4FhjpVBkHQT7AM9oAQxG+3kRLBjesq1Rwfiqw4/GTafDW+PFrjZsqHO5HpfPDeX7DiQgD84yc2+tJyaMG+wgvAPCc3VkAxMLBzCA8FA4/MfKDeuWi/fkd5qug=
  slack:
    secure: Zv7IDpflG7K+LBvY+dcJUzq0oVou+eusDI1xK8zIN2z+8c/qX2pGhUPyUuW/2MSP2LOJb7Ddiw9ssMMyDCi469mzFivJzt7q/ln9NdiVsl+5gmvNtCjImQ9Pt0qM7EkYPRk8ZA1Te3TuGLGZG88GbCAVaxN2etrx9UlSGgDhZfY=

# Deployment
after_success: >
  if ([ ! -z "$DEPLOY_TOKEN" ] &&
      [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ] &&
      [ -z "$TRAVIS_TAG" ] &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    echo "Deploying";
    git config --global user.email "$DEPLOY_EMAIL";
    git config --global user.name "$DEPLOY_NAME";
    git remote rm origin;
    git remote add origin "https://$DEPLOY_USER:$DEPLOY_TOKEN@github.com/$TRAVIS_REPO_SLUG.git";
    npm run-script deploy;
    echo "Deployed";
  else
    echo "Skipped deploy"
  fi

# Custom Configuration
env:
  global:
    # deployment environment variables
    # travis encrypt "DEPLOY_USER=$GITHUB_USERNAME" --add env.global
    # travis encrypt "DEPLOY_TOKEN=$GITHUB_TRAVIS_TOKEN" --add env.global
    - DEPLOY_BRANCH='2012+'  # this is the branch name that you want tested and deployed, set correctly
    - DEPLOY_NAME='Travis CI Deployer'  # this is the name that is used for the deployment commit, set to whatever
    - DEPLOY_EMAIL='deployer@travis-ci.org'  # this is the email that is used for the deployment commit, set to whatever
    - secure: XoGrisVXehIVss06+JIn86WancOhiHLiph4BCkf9QhwYFHyS3xx8vATrvoBrTijHOn6AgCIXBM1oRJ06/a3GrZzH2VwiEJYD6miV3ppn9IcaxFu5Pp8rqtYMfkxLRKl84V3kFKzbQJusW6z7dQrbyGGdM9CD1akK8hKciQg52Nc=
    - secure: dMCVH4gIFVKIAuH3AgIa5ZfXmVCvIKfkLQUbdTi9iIMHQye+MZVstygyZpO4GybLQKcADmaB6mvR9NXlgyLHRwcqLWSQ30YN5urCvS7XBOgwicyXGGGwSFe8PynsJb7uEIRGWQ01PSUPVHVg+GIkdEHyzYyvk9SSxaOeJSbH6ew=
    # application environment variables
    # travis encrypt "BEVRY_GITHUB_CLIENT_ID=$BEVRY_GITHUB_CLIENT_ID" --add env.global
    # travis encrypt "BEVRY_GITHUB_CLIENT_SECRET=$BEVRY_GITHUB_CLIENT_SECRET" --add env.global
    - secure: i20XQubNOUr4M4O56Oc09q/XSJxjhpQZBuexaR12PBhGzHaDF+FKkunb6KjQskDey/XnrvQvNfIt6DZu0Hijr9Hy1+mbiag8J9Vw99Ui/NkiJT5TDtuJJCYO9TRTtGN/Kwj7gpo7+Qbws1s+jK1IF3I9BWGrbJd89dcvz64fdTQ=
    - secure: U59F72ZpHRXn2/AK+YY34gsYt6s2Bj444SEyhrwEtVIoS7uztp+7Z0oFSjbrnz9cmnr5m7iuICO0kK8Q34LpFjrLN5V5O9VC8tgUr/vQA6bzevOX56tAd47bs/Rt+8ifc7sIkomcej2hNjiONEFFDx/kjv4FWCK393xFnqWyzFo=
