# 2017 May 26
# https://docpad.org/docs/deploy
# https://github.com/balupton/awesome-travis
sudo: false
language: node_js
node_js:
- "7"
cache:
  directories:
    - $HOME/.npm  # npm's cache
    - $HOME/.yarn-cache  # yarn's cache
before_script:
- npm run our:verify
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-deploy.bash)"
notifications:
  slack:
    secure: dB/hr2zM4EJhc2dt4Ghuu0/Y/oS3exFMZUlEH1aebKkmSDEcuPhQygCxi4SGJ11hVjopZCJfiUzUBuG9VzdA5m8slQvv6iJBFqbuENB4lmnDsBEyMgOLeazfDx5bHAUQVKKvdg7kOQV/O95vohf4twvTD7WgF8X964evsSq5woU=
  email:
    recipients:
      secure: MEX104fRox/z4vj+bMQNAdv0Co2HoSOWs7Lgpu5/entJDApSxKGo1WefOdLQ6atBU/b3Zw2hVDa0qNj1vpDhsL93aIV2vIZY+mkWb15eTaKggJYRnONMQPUdVM07enm7ZFntd3wSeuKL44MdKTIwmS26G01RkzpqoasEP1C1c2Q=
