sudo: false
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/node-verify.bash)"
notifications:
  email:
    recipients:
      secure: ajX1Xyn2v7ED2CPL/cG8QBpPHPPqQsavmPNlQp3qyK7W38b6MQYqM6fFlMmZm0wqMSsltupiGxjyz9FgS24EfWrY7c/4+cBeN/RphAUWonBjdktwiV3gcwxbJU8eaO88TzIp2ahesX+uQmTs+UzRhMziLALRolzjfDWegmUvvLA=
